import { useEffect, useState } from "react";
import type { ChangeEvent, FormEvent } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { Loader2, UploadCloud, X } from "lucide-react";
import { addLocation, getCategories, getLocations, updateLocation, uploadLocationImage } from "../../lib/store";
import { usStates } from "../../data/usStates";
import LoadingState from "../../components/LoadingState";
import ErrorState from "../../components/ErrorState";
import type { LocationItem } from "../../types";

type FormState = { venue: string; city: string; state: string; region: string; image: string; address: string };
const emptyForm: FormState = { venue: "", city: "", state: "", region: "", image: "", address: "" };
const inputClass = (error?: string) => `mt-2 w-full rounded-lg border px-3 py-2.5 text-sm focus:outline-none ${error ? "border-red-400" : "border-paper-line focus:border-gold"}`;
function Field({ label, required, error, children }: { label: string; required?: boolean; error?: string; children: React.ReactNode }) { return <div><label className="text-sm font-medium text-ink">{label}{required ? " *" : ""}</label>{children}{error && <p className="mt-1 text-xs text-red-500">{error}</p>}</div>; }

export default function LocationForm() {
  const { id } = useParams(); const navigate = useNavigate(); const isEdit = Boolean(id);
  const [form, setForm] = useState<FormState>(emptyForm); const [regions, setRegions] = useState<string[] | null>(null); const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState(""); const [errors, setErrors] = useState<Record<string,string>>({}); const [uploading, setUploading] = useState(false); const [uploadError, setUploadError] = useState(""); const [submitting, setSubmitting] = useState(false); const [submitError, setSubmitError] = useState("");
  function set<K extends keyof FormState>(key: K, value: FormState[K]) { setForm((current) => ({ ...current, [key]: value })); }
  useEffect(() => { let active=true; Promise.all([getCategories(), isEdit ? getLocations() : Promise.resolve([])]).then(([cats, locations]) => { if(!active) return; setRegions(cats); if(isEdit){ const existing=(locations as LocationItem[]).find((item)=>item.id===id); if(!existing){setLoadError("That location couldn't be found."); return;} setForm({venue:existing.venue,city:existing.city,state:existing.state,region:existing.region,image:existing.image||"",address:existing.address||""}); }}).catch((err)=>setLoadError(err.message||"Couldn't load location data.")).finally(()=>active&&setLoading(false)); return ()=>{active=false;}; }, [id,isEdit]);
  async function handleFileChange(e: ChangeEvent<HTMLInputElement>) { const file=e.target.files?.[0]; if(!file)return; if(!file.type.startsWith("image/")){setUploadError("Please choose an image file.");return;} setUploading(true);setUploadError(""); try{set("image",await uploadLocationImage(file));}catch(err){setUploadError(err instanceof Error?err.message:"Couldn't upload that image.");}finally{setUploading(false);e.target.value="";} }
  function validate(){const next:Record<string,string>={};if(!form.venue.trim())next.venue="Venue name is required.";if(!form.city.trim())next.city="City is required.";if(!form.state)next.state="State is required.";if(!form.region)next.region="Choose a region.";setErrors(next);return Object.keys(next).length===0;}
  async function handleSubmit(e:FormEvent){e.preventDefault();if(!validate())return;setSubmitting(true);setSubmitError("");try{if(isEdit&&id)await updateLocation(id,form);else await addLocation(form);navigate("/admin/locations");}catch(err){setSubmitError(err instanceof Error?err.message:"Couldn't save this location.");setSubmitting(false);}}
  if(loadError)return <ErrorState message={loadError} onRetry={()=>window.location.reload()} />; if(loading||!regions)return <LoadingState label="Loading location form…" />;
  return <div>
    <div className="flex items-start justify-between gap-4"><div><h1 className="font-display text-2xl font-semibold text-black sm:text-3xl">{isEdit?"Edit location":"Add location"}</h1><p className="mt-1 text-sm text-ink-soft">{isEdit?"Update this parking venue.":"Add a parking venue to the public location directory."}</p></div><Link to="/admin/locations" className="text-sm font-semibold text-ink-soft hover:text-black">Back to locations</Link></div>
    <form onSubmit={handleSubmit} noValidate className="mt-6 max-w-2xl space-y-6">
      <Field label="Venue name" required error={errors.venue}><input value={form.venue} onChange={(e)=>set("venue",e.target.value)} className={inputClass(errors.venue)} placeholder="e.g. Mercedes-Benz Stadium" /></Field>
      <Field label="Parking location image"><div className="mt-2 flex flex-col gap-4 sm:flex-row"><div className="relative h-32 w-full shrink-0 overflow-hidden rounded-lg border border-paper-line bg-paper-stub sm:w-48">{form.image?<><img src={form.image} alt="" className="h-full w-full object-cover"/><button type="button" onClick={()=>set("image","")} className="absolute right-1.5 top-1.5 rounded-full bg-black/70 p-1 text-white" aria-label="Remove image"><X size={13}/></button></>:<div className="flex h-full items-center justify-center text-xs text-ink-soft/60">No photo yet</div>}{uploading&&<div className="absolute inset-0 flex items-center justify-center bg-white/80"><Loader2 size={20} className="animate-spin text-gold-dark"/></div>}</div><div className="flex-1 space-y-3"><label className="flex w-fit cursor-pointer items-center gap-2 rounded-lg border border-dashed border-paper-line px-4 py-2.5 text-sm font-medium text-ink-soft hover:border-gold hover:text-gold-dark"><UploadCloud size={16}/>Upload a photo<input type="file" accept="image/*" onChange={handleFileChange} className="hidden"/></label>{uploadError&&<p className="text-xs text-red-500">{uploadError}</p>}<input value={form.image} onChange={(e)=>set("image",e.target.value)} placeholder="Or paste an image URL" className={inputClass()}/></div></div></Field>
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><Field label="City" required error={errors.city}><input value={form.city} onChange={(e)=>set("city",e.target.value)} className={inputClass(errors.city)} placeholder="Atlanta"/></Field><Field label="State" required error={errors.state}><select value={form.state} onChange={(e)=>set("state",e.target.value)} className={inputClass(errors.state)}><option value="">Select state</option>{usStates.map((state)=><option key={state} value={state}>{state}</option>)}</select></Field></div>
      <Field label="Region" required error={errors.region}><select value={form.region} onChange={(e)=>set("region",e.target.value)} className={inputClass(errors.region)}><option value="">Select region</option>{regions.map((region)=><option key={region} value={region}>{region}</option>)}</select><p className="mt-1 text-xs text-ink-soft">Regions are managed from the Regions section.</p></Field>
      <Field label="Street address"><input value={form.address} onChange={(e)=>set("address",e.target.value)} className={inputClass()} placeholder="Optional venue address"/></Field>
      {submitError&&<p className="text-sm text-red-500">{submitError}</p>}<button type="submit" disabled={submitting||uploading} className="rounded-full bg-gold px-7 py-3 text-sm font-semibold text-black hover:bg-gold-light disabled:opacity-60">{submitting?"Saving…":isEdit?"Save changes":"Add location"}</button>
    </form>
  </div>;
}
